<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="../styles/main.css" rel="stylesheet">
<link href="../styles/login.css" rel="stylesheet">
<!------ Include the above in your HEAD tag ---------->

<div class="wrapper fadeInDown">
    <div id="formContent">
        <!-- Login Form -->
        <form method="post">
            <input type="text" id="mail" class="fadeIn second" name="mail" placeholder="mail">
            <input type="password" id="password" class="fadeIn third" name="password" placeholder="password">
            <input type="password" id="password2" class="fadeIn third" name="password2" placeholder="repeat password">
            <input type="submit" class="fadeIn fourth" value="Sign up">
        </form>

    </div>
</div>